### ISSUE TITLE
Review, Mar 4 2025

### ISSUE THREAD

**Issue by SlavaMelanko** [Maksimka66/massive-task#1]
# Review, Mar 4 2025

## 1. Project structure and file naming

Current structure is fine but can be simpler:

<img width="239" alt="Image" src="https://github.com/user-attachments/assets/3a820b82-8d60-4d21-8180-0562fd82ae65" />

Why `index.tsx`? Allows importing with `import Input from '../Input'` instead of `import Input from '../Input/Input'`
Why `styles.scss`? Keeps imports clean:

```jsx
import './styles.scss' // Shorter and cleaner IMO

export default function Button({ children, type, className }: IButtonStyles) {
// ...
```

## 2. styles.scss

1. Fix the following warning:

```bash
Deprecation Warning [import]: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
1 │ @import "../../styles/variables";
```

It's better without warnings in the project. Use `@use` instead:

```js
@use '../../styles/variables' as vars;

.button {
  font-family: vars.$font-montserrat;
  // ...
```

2. Use BEM methodology correctly:

```scss
@use '../../styles/variables' as vars;

.button {
  font-family: vars.$font-montserrat;
  border-radius: 25px;
  height: 36px;
  min-width: 300px;
  cursor: pointer;
  display: flex;
  align-items: center;
  font-size: 14px;
  font-weight: 700;
  justify-content: center;
  letter-spacing: 0.25px;
  line-height: 24px;
  outline: none;
  padding: 5px 19px;
  text-align: center;
  border: none;

  &--submit {
    color: vars.$text-color-default;
    background-color: vars.$tomato-color;
  }

  &--google {
    background-color: vars.$white;
    color: vars.$black;
    border: 1px solid vars.$black;
  }
}
```

Some more theory:

<img width="1014" alt="Image" src="https://github.com/user-attachments/assets/458c784d-a19e-4573-ab21-6d853a579f5c" />

Input example:

```scss
@use "../../styles/variables" as vars;

.input {
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  justify-content: center;
  gap: 10px;
  width: 100%;
  margin-bottom: 1.25rem;

  &__label {
    font-family: vars.$font-montserrat;
    font-size: 14px;
    font-weight: 700;
    letter-spacing: 0.321429px;
    line-height: 1.4;

    &::after {
      content: "*";
      margin-left: 6px;
      color: vars.$tomato-color;
    }
  }

  &__field {
    background-color: vars.$background-color;
    border: 1px solid vars.$border-input-color;
    width: 100%;
    border-radius: 0.25rem;
    font-size: 14px;
    line-height: 1.4;
    padding: 0.5rem;

    &::placeholder {
      font-family: vars.$font-montserrat;
    }
  }

  &__error {
    position: absolute;
    bottom: -24px;
    color: #f80e0e;
    font-size: 12px;
    line-height: 1rem;
    display: block;
    font-family: vars.$font-montserrat;
  }
}
```

3. Import and apply styles:

```jsx
import './styles.scss'

export default function Button({ children, type, className }: IButtonStyles) {
  return (
    <button className={`button ${className}`} type={type}> // Potential bug, because className can be 'undefined'
      {children}
    </button>
  )
}
```

## 3. index.jsx

1. Handle conditional class names cleanly using clsx:

```jsx
import clsx from 'clsx'

import './styles.scss'

export default function Button({ children, type, className }: IButtonStyles) {
  return (
    <button className={clsx('button', className)} type={type}>
      {children}
    </button>
  )
}
```

And Input as an example:

```jsx
import { IFieldProps } from '../../types/interfaces'
import clsx from 'clsx'

import './styles.scss'

export default function Input({
  type,
  placeholder,
  label,
  error,
  register,
  id,
  containerStyle,
  inputStyle,
  labelStyle,
}: IFieldProps) {
  return (
    <div className={clsx('input', containerStyle)}>
      {label && (
        <label htmlFor={id} className={clsx('input__label', labelStyle)}>
          {label}
        </label>
      )}
      <input
        className={clsx('input__field', inputStyle)}
        id={id}
        type={type}
        placeholder={placeholder}
        {...register}
      />
      {error && <span className="input__error">{error}</span>}
    </div>
  )
}
```

## 4. Unit tests

Here are some key test cases we can add for Button:

1. Renders correctly with children
2. Applies the correct class names
3. Renders with the correct type attribute
4. Handles click events correctly
5. Handles missing props gracefully
